added favorite food to repo

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -13,6 +13,14 @@ jobs:
         uses: actions/setup-python@v5
         with:
           python-version: '3.10'
+      - name: Check if main.py exists
+        run: |
+          if [ ! -f main.py ]; then
+            echo "main.py not found!"
+            exit 1
+          else
+            echo "main.py found."
+          fi
 
       - name: Run script
         run: python main.py
